name: CI/CD - Deploy ShortenApp & ShortenFunction

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-frontend:
    name: Deploy Frontend (ShortenApp)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Azure Static Web Apps CLI
        run: npm install -g @azure/static-web-apps-cli

      - name: Build ShortenApp
        run: |
          cd ShortenApp
          dotnet publish -c Release -o publish

      - name: Deploy to Azure Static Web Apps
        run: |
          cd ShortenApp
          swa deploy ./publish/wwwroot -n ${{ secrets.AZURE_STATIC_WEBAPP_NAME }} --env production

  deploy-backend:
    name: Deploy Backend (ShortenFunction)
    runs-on: ubuntu-latest
    needs: deploy-frontend  # Se ejecuta después de desplegar el frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Login to Azure
        run: az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}

      - name: Set Azure Function App Settings
        run: |
          az functionapp config appsettings set -g ${{ secrets.AZURE_RESOURCE_GROUP }} -n ${{ secrets.AZURE_FUNCTIONAPP_NAME }} --settings FUNCTIONS_INPROC_NET8_ENABLED=1

      - name: Set Azure SQL Connection String
        run: |
          az webapp config connection-string set -g ${{ secrets.AZURE_RESOURCE_GROUP }} -n ${{ secrets.AZURE_FUNCTIONAPP_NAME }} -t sqlazure --settings ShortenDB="Data Source=${{ secrets.AZURE_SQL_SERVER }};User ID=${{ secrets.AZURE_SQL_USER }};Password=${{ secrets.AZURE_SQL_PASSWORD }};Database=shorten"

      - name: Build ShortenFunction
        run: |
          cd ShortenFunction
          dotnet publish -c Release -o publish

      - name: Create Deployment Package
        run: |
          cd ShortenFunction/publish
          zip -r functionapp.zip .

      - name: Deploy Function App to Azure
        run: |
          az functionapp deployment source config-zip -g ${{ secrets.AZURE_RESOURCE_GROUP }} -n ${{ secrets.AZURE_FUNCTIONAPP_NAME }} --src ShortenFunction/publish/functionapp.zip --verbose
