name: Sync Changes in src to Mirror

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'  # Solo se ejecuta si hay cambios en la carpeta src

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio principal
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Para obtener el historial completo

      - name: Configurar usuario de Git
        run: |
          git config --global user.email "jv2020066920@virtual.upt.pe"
          git config --global user.name "JeanValverde24"

      - name: Clonar repositorio espejo
        run: |
          git clone https://JeanValverde24:${{ secrets.SECRET_GIT_PAT }}@github.com/JeanValverde24/Repo_Mirror_lab_u3_01.git repo_espejo
          cd repo_espejo
          git checkout main

      - name: Copiar solo la carpeta src al repositorio espejo
        run: |
          cd repo_espejo
          rm -rf src  # Eliminar src existente en el repositorio espejo para evitar conflictos
          cp -r ../src .

      - name: Confirmar y enviar los cambios al espejo
        run: |
          cd repo_espejo
          git add src
          if git diff --cached --quiet; then
            echo "No hay cambios en la carpeta src, no se realizará el push."
            exit 0
          fi
          git commit -m "Sync: Actualización de la carpeta src"
          git push --force origin main

      - name: Agregar enlace del repositorio espejo al summary
        run: |
          echo "El enlace del repositorio espejo es: https://github.com/JeanValverde24/Repo_Mirror_lab_u3_01" >> $GITHUB_STEP_SUMMARY
